### ISSUE TITLE
tokenizer.bos_token_id 为啥不正确呢？

### ISSUE THREAD

**Issue by sjyttkl** [liucongg/ChatGLM-Finetuning#112]
Traceback (most recent call last):
  File "/root/share/project/ChatGLM-Finetuning/train.py", line 235, in <module>
    main()
  File "/root/share/project/ChatGLM-Finetuning/train.py", line 134, in main
    train_dataset = MODE[args.mode]["dataset"](args.train_path, tokenizer, args.max_len, args.max_src_len, args.is_skip)
  File "/root/share/project/ChatGLM-Finetuning/utils.py", line 51, in __init__
    context_length = input_ids.index(tokenizer.bos_token_id)
ValueError: None is not in list

**Comment by liucongg** [comment]
看一下，可能是模型文件没有更新

**Comment by BertieGo** [comment]
我也碰到了这个问题，我是在 modelscope 下载的 chatglm3-6b，然后依赖什么都下载好了，微调的时候运行 ChatGML 的 train.sh 就会报这个错，快崩溃了
