### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by ZCzzzzzz** [liucongg/ChatGLM-Finetuning#146]
我在使用vllm0.5.0测试chatglm-6b的性能，一开始运行vllm时出现“AttributeError: ‘ChatGLMTokenizer‘ object has no attribute ‘tokenizer‘”的错误，把chatglm-6b中的tokenization_chatglm.py替换了之后运行vllm的benchmark_throughput.py时又出现如下错误，请问怎么解决？
![Uploading chatglm报错.png…]()

**Comment by ZCzzzzzz** [comment]
Traceback (most recent call last):
  File "/workspace/zc/vllm-0.5.0/benchmarks/benchmark_throughput.py", line 411, in <module>
    main(args)
  File "/workspace/zc/vllm-0.5.0/benchmarks/benchmark_throughput.py", line 211, in main
    tokenizer = AutoTokenizer.from_pretrained(
  File "/usr/local/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 882, in from_pretrained
    return tokenizer_class.from_pretrained(
  File "/usr/local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2271, in from_pretrained
    return cls._from_pretrained(
  File "/usr/local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2505, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/tokenization_chatglm.py", line 89, in __init__
    self.tokenizer = SPTokenizer(vocab_file)
  File "/root/.cache/huggingface/modules/transformers_modules/tokenization_chatglm.py", line 14, in __init__
    assert os.path.isfile(model_path), model_path
  File "/usr/local/lib/python3.10/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
