### ISSUE TITLE
RuntimeError: Expected 4-dimensional input for 4-dimensional weight

### ISSUE THREAD

**Issue by eight-corner** [liucongg/ChatGLM-Finetuning#39]
Traceback (most recent call last):
  File "predict_lora.py", line 105, in <module>
    main()
  File "predict_lora.py", line 44, in main
    model.eval()
  File "/home/kas/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1926, in eval
    return self.train(False)
  File "/home/kas/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1907, in train
    module.train(mode)
  File "/home/kas/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1907, in train
    module.train(mode)
  File "/home/kas/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1907, in train
    module.train(mode)
  [Previous line repeated 4 more times]
  File "/home/kas/.local/lib/python3.7/site-packages/peft/tuners/lora.py", line 420, in train
    groups=sum(self.enable_lora),
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [8192, 8, 1, 1], but got 3-dimensional input of size [1, 16, 4096] instead
推理的时候报错了，请问是什么原因？

**Comment by darkwhale** [comment]
同样遇到这个问题，老哥解决了吗

**Comment by liucongg** [comment]
两个办法，关掉model.eval()，或者在保持模型文件adapter_config.json中，将inference_mode参数改为False

**Comment by MaiziXiao** [comment]
> 两个办法，关掉model.eval()，或者在保持模型文件adapter_config.json中，将inference_mode参数改为False

设为False后，model.eval()还是报错。。

**Comment by liucongg** [comment]
> > 两个办法，关掉model.eval()，或者在保持模型文件adapter_config.json中，将inference_mode参数改为False
> 
> 设为False后，model.eval()还是报错。。

按道理不应该呀，你把model.eval()去掉可以吗？
