### ISSUE TITLE
提示[MASK] is already defined. 训练启动失败

### ISSUE THREAD

**Issue by KOD-Chen** [liucongg/ChatGLM-Finetuning#46]
Some weights of ChatGLMForConditionalGeneration were not initialized from the model checkpoint at /ProjectRoot/ChatGLM/chatglm_tuning/chatglm-6b/ and are newly initialized: ['transformer.prefix_encoder.trans.0.bias', 'transformer.prefix_encoder.trans.0.weight', 'transformer.prefix_encoder.trans.2.weight', 'transformer.prefix_encoder.trans.2.bias', 'transformer.prefix_encoder.embedding.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "finetuning_pt.py", line 150, in <module>
    main()
  File "finetuning_pt.py", line 66, in main
    tokenizer = ChatGLMTokenizer.from_pretrained(args.model_dir)
  File "/usr/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 1820, in from_pretrained
    **kwargs,
  File "/usr/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 1965, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/ProjectRoot/ChatGLM/chatglm_tuning/tokenization_chatglm.py", line 212, in __init__
    self.sp_tokenizer = SPTokenizer(vocab_file)
  File "/ProjectRoot/ChatGLM/chatglm_tuning/tokenization_chatglm.py", line 32, in __init__
    self.text_tokenizer = self._build_text_tokenizer(encode_special_tokens=False)
  File "/ProjectRoot/ChatGLM/chatglm_tuning/tokenization_chatglm.py", line 66, in _build_text_tokenizer
    tokenizer, self.special_tokens, self.max_blank_length, self.byte_fallback, encode_special_tokens
  File "/ProjectRoot/ChatGLM/chatglm_tuning/tokenization_chatglm.py", line 61, in _configure_tokenizer
    text_tokenizer.refresh()
  File "/usr/lib/python3.7/site-packages/icetk/text_tokenizer.py", line 31, in refresh
    self.sp.Load(model_proto=self.proto.SerializeToString())
  File "/usr/lib/python3.7/site-packages/sentencepiece-0.1.97-py3.7-linux-x86_64.egg/sentencepiece/__init__.py", line 904, in Load
    return self.LoadFromSerializedProto(model_proto)
  File "/usr/lib/python3.7/site-packages/sentencepiece-0.1.97-py3.7-linux-x86_64.egg/sentencepiece/__init__.py", line 250, in LoadFromSerializedProto
    return _sentencepiece.SentencePieceProcessor_LoadFromSerializedProto(self, serialized)
RuntimeError: Internal: [MASK] is already defined.

**Comment by Ji3xiangLi** [comment]
应该是模型版本问题，用作者提供的百度云链接里的文件替换，github里的文件就可以正常运行了

**Comment by KOD-Chen** [comment]
> 应该是模型版本问题，用作者提供的百度云链接里的文件替换，github里的文件就可以正常运行了

感谢感谢，解决了
