### ISSUE TITLE
有报错这个的老哥吗CUDA error: invalid device ordinal，这个怎么解决呢

### ISSUE THREAD

**Issue by xxtyy** [liucongg/ChatGLM-Finetuning#74]
Traceback (most recent call last):
  File "/home/administrator/ChatGLM-Finetuning/predict_freeze.py", line 106, in <module>
    main()
  File "/home/administrator/ChatGLM-Finetuning/predict_freeze.py", line 44, in main
    model.half().to("cuda:{}".format(args.device))
  File "/home/administrator/ChatGLM-Finetuning/venv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1749, in to
    return super().to(*args, **kwargs)
  File "/home/administrator/ChatGLM-Finetuning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 989, in to
    return self._apply(convert)
  File "/home/administrator/ChatGLM-Finetuning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  File "/home/administrator/ChatGLM-Finetuning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  File "/home/administrator/ChatGLM-Finetuning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 664, in _apply
    param_applied = fn(param)
  File "/home/administrator/ChatGLM-Finetuning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 987, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by xxtyy** [comment]
![image](https://github.com/liucongg/ChatGLM-Finetuning/assets/128583103/f7a60c40-1511-4536-9061-4e5fd54374db)

**Comment by xxtyy** [comment]
这不会是我显存不够吧
