### ISSUE TITLE
无法加载Freeze训练后的模型

### ISSUE THREAD

**Issue by CaRRotOne** [liucongg/ChatGLM-Finetuning#84]
output目录如下：

> -rw-r--r-- 1 user user 1.3K Aug 11 15:49 config.json
-rw-r--r-- 1 user user  111 Aug 11 15:49 generation_config.json
-rw-r--r-- 1 user user 9.4G Aug 11 15:49 pytorch_model-00001-of-00002.bin
-rw-r--r-- 1 user user 2.4G Aug 11 15:49 pytorch_model-00002-of-00002.bin
-rw-r--r-- 1 user user  20K Aug 11 15:49 pytorch_model.bin.index.json
-rw-r--r-- 1 user user    3 Aug 11 15:49 special_tokens_map.json
-rw-r--r-- 1 user user 995K Aug 11 15:49 tokenizer.model
-rw-r--r-- 1 user user  211 Aug 11 15:49 tokenizer_config.json

运行时加载tokenizer报错：

```
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/home/user/ChatGLM-6B/web_demo2.py", line 72, in <module>
    st.session_state["state"] = predict(prompt_text, max_length, top_p, temperature, st.session_state["state"])
  File "/home/user/ChatGLM-6B/web_demo2.py", line 26, in predict
    tokenizer, model = get_model()
  File "/home/user/.local/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 211, in wrapper
    return cached_func(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 240, in __call__
    return self._get_or_create_cached_value(args, kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 266, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 320, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
  File "/home/user/ChatGLM-6B/web_demo2.py", line 15, in get_model
    tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
  File "/home/user/.local/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 676, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class ChatGLMTokenizer does not exist or is not currently imported.
```

**Comment by liucongg** [comment]
将tokenizer文件copy到模型路径即可
